#!/bin/bash

backupdir=/var/backups/mysql
unixtimestamp=$(date '+%s')
day=$(date -d "@${unixtimestamp}" '+%F')
hour=$(date -d "@${unixtimestamp}" '+%R')

removedir() {     
    echo "Removing $1 ..."
    [[ -d "$1" ]] && rm -r $1
}

[[ ! -d ${backupdir}/${day}/${hour} ]] && mkdir -p ${backupdir}/${day}/${hour}/dumps

#Create a full backup
if [[ "${hour}" =~ (00|03|06|09|12|15|18|21):00 ]]
then
    logfile=$(mktemp)
    echo "Creating full backup..."
    /usr/bin/innobackupex --no-timestamp --databases "cloud cloud_usage" --slave-info --safe-slave-backup --no-lock ${backupdir}/${day}/${hour}/full >${logfile} 2>&1
    mv ${logfile} ${backupdir}/${day}/${hour}/full/innobackupex.log
fi

#Create dumps
logfile=$(mktemp)
for database in $(mysql -sNe "show databases" | grep -vE 'information_schema|performance_schema')
do
    echo "Dumping database ${database} ..." | tee -a ${logfile}
    mysqldump -E ${database} 2>> ${logfile} | gzip > ${backupdir}/${day}/${hour}/dumps/${database}.sql.gz
done
mv ${logfile} ${backupdir}/${day}/${hour}/dumps/mysqldump.log


echo "Cleanup..."

if [[ "${hour}" == "00:00" ]]
then
    # Delete the folder from 8 days ago, unless it is the 1st, 8th, 15th, 22th or 29th .
    if [[ ! "$(date -d "${date}" '+%d')" =~ (01|08|15|22|29)$ ]]
    then
        removedir ${backupdir}/$(date -d "@$[ unixtimestamp - 8 * 86400 ]" '+%F')
    fi
else
    # Delete the folder from 96 hours ago
    removedir ${backupdir}/$(date -d "@$[ unixtimestamp - 4 * 86400 ]" '+%F')/${hour} 
fi

# Delete the folder from 48 hours ago, unless it is on each 6th hour .
if [[ "${hour}" =~ (03|09|15|21):00 ]]
then
    removedir ${backupdir}/$(date -d "@$[ unixtimestamp - 2 * 86400 ]" '+%F')/${hour}
fi

# Delete the folder from 24 hours ago, unless it is on each 3rd hour .
if [[ ! "${hour}" =~ (00|03|06|09|12|15|18|21):00 ]]
then
    removedir ${backupdir}/$(date -d "@$[ unixtimestamp - 86400 ]" '+%F')/${hour}
fi
