#!/bin/bash

logfile=$(mktemp)
backupdir=/var/backups/mysql
day=$(date '+%F')
unixtimestamp=$(date '+%s')
hour=$(date '+%R')

[ ! -d ${backupdir}/${day}/${hour} ] && mkdir -p ${backupdir}/${day}/${hour}/dumps

if [[ "${hour}" == "00:00" ]]
then
    /usr/bin/innobackupex --no-timestamp --databases "cloud cloud_usage" --slave-info --safe-slave-backup --no-lock ${backupdir}/${day}/${hour}/full >${logfile} 2>&1
    mv ${logfile} ${backupdir}/${day}/${hour}/full/innobackupex.log
fi

for database in $(mysql -sNe "show databases" | grep -vE 'information_schema|performance_schema')
do 
    echo "$(date '+%F %T') Dumping database ${database} ..." | tee -a ${logfile}
    mysqldump -E ${database} 2>> ${logfile} | gzip > ${backupdir}/${day}/${hour}/dumps/${database}.sql.gz
done
mv ${logfile} ${backupdir}/${day}/${hour}/dumps/mysqldump.log

# cleanup

# Delete the folder from 8 days ago, unless it is the 1st, 8th, 15th, 22th or 29th .

date=$(date -d "@$[ unixtimestamp - 8 * 86400 ]" '+%F')
dayofthemonth=$(date -d "${date}" '+%d')

case "${dateofthemonth}" in
    01|08|15|22|29)
        for dir in $(ls -d ${backupdir}/${date}/* 2>/dev/null | grep -v '00:00')
        do
            rm -r "${dir}"
        done 
        ;;
    *)
        rm -r ${backupdir}/${date}
        ;;
esac

# Delete the folder from 24 hours ago, unless it is on each 3rd hour . 
